-- Script generated by SimpleSpy - credits to exxtremewa#9394
-- This generator is IN DEVELOPMENT, not compatible with all types/classes yet

local args = {
    [1] = "MY NAME IS ROO_Y AND IM EXPLOITING RIGHT NOW",
    [2] = "All",
}

game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack(args))
wait(0.5)
local args = {
    [1] = "MY NAME IS ROO_Y AND IM EXPLOITING RIGHT NOW",
    [2] = "All",
}

game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack(args))
wait(0.5)
local args = {
    [1] = "MY NAME IS ROO_Y AND IM EXPLOITING RIGHT NOW",
    [2] = "All",
}

game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack(args))
wait(0.5)
local args = {
    [1] = "MY NAME IS ROO_Y AND IM EXPLOITING RIGHT NOW",
    [2] = "All",
}

game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack(args))
wait(0.5)
local args = {
    [1] = "MY NAME IS ROO_Y AND IM EXPLOITING RIGHT NOW",
    [2] = "All",
}

game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack(args))
wait(0.5)
local args = {
    [1] = "MY NAME IS ROO_Y AND IM EXPLOITING RIGHT NOW",
    [2] = "All",
}

game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack(args))
wait(0.5)
local args = {
    [1] = "MY NAME IS ROO_Y AND IM EXPLOITING RIGHT NOW",
    [2] = "All",
}

game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack(args))
wait(0.5)
local args = {
    [1] = "MY NAME IS ROO_Y AND IM EXPLOITING RIGHT NOW",
    [2] = "All",
}

game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack(args))
wait(0.5)
local args = {
    [1] = "MY NAME IS ROO_Y AND IM EXPLOITING RIGHT NOW",
    [2] = "All",
}

game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack(args))
wait(0.5)
local args = {
    [1] = "MY NAME IS ROO_Y AND IM EXPLOITING RIGHT NOW",
    [2] = "All",
}

game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack(args))
wait(0.5)
local args = {
    [1] = "MY NAME IS ROO_Y AND IM EXPLOITING RIGHT NOW",
    [2] = "All",
}

game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack(args))
wait(0.5)
local args = {
    [1] = "MY NAME IS ROO_Y AND IM EXPLOITING RIGHT NOW",
    [2] = "All",
}

game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack(args))
